export default [
  "Management",
  "Marketing",
  "Finance",
  "Human Resources",
  "Software Development",
  "Data Science",
  "Information Technology",
  "Cybersecurity",
  "Nursing",
  "Medicine",
  "Pharmacy",
  "Public Health",
  "Teaching",
  "Administration",
  "Special Education",
  "Mechanical",
  "Electrical",
  "Civil",
  "Software Engineering",
  "Graphic Design",
  "Fine Arts",
  "Fashion Design",
  "Photography",
  "Biology",
  "Chemistry",
  "Physics",
  "Environmental Science",
  "Social Work",
  "Psychology",
  "Counseling",
  "Nonprofit Management",
  "Law",
  "Paralegal Studies",
  "Criminal Justice",
  "Public Policy",
  "Carpentry",
  "Plumbing",
  "Event Planning",
];
